#include <QtGui>
#include <QPushButton>
#include <QWidget>
#include <QDialog>
#include <QTableView>
#include <QHeaderView>
#include <QSqlRelationalTableModel>
#include <QSqlRelationalDelegate>
#include <QMessageBox>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QTextEdit>
#include <QSpinBox>
#include <QComboBox>
#include <QPushButton>
#include <QtWidgets>
#include <QSizePolicy>
#include <QLayout>
#include <QHeaderView>
#include <QtCore>
#include <QtSql>
#include <QSqlQuery>
#include <QSqlError>
#include <QMainWindow>
